name = "HighVoronoi"
uuid = "1d30c219-805f-47bd-9cb8-33f291c94a4c"
authors = ["Martin Heida"]
version = "1.0.0-DEV"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
